version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - run: cat /etc/os-release
      - run: echo "a"
      - run: |
          echo About to pull Cypress docker image
          echo About to pull Cypress docker image > /tmp/tmp.log
          jq -r .devDependencies.cypress package.json
          docker pull cypress/included:13.6.0
